### ISSUE TITLE
flow/jsonpath abandoned

### ISSUE THREAD

**Issue by martinssipenko** [SoftCreatR/JSONPath#2]
Hi,

I reached out to maintainers of `flow/jsonpath` to understand if the package is still maintained. They got back to me and said that they do not plan to maintain it going further. I reached out because I wanted to propose to them that I could take over, but later noticed you already kind of did that by forking `flow/jsonpath`. So given I had open communication with them I created a pull request https://github.com/FlowCommunications/JSONPath/pull/60 which marks `flow/jsonpath` as abandoned and suggests using your package.

I've also added comments to all existing issues and pull requests on the original repo stating that they should open a new ticket or PR if the issue is still relevant.

The old project will be archived soon.

**Comment by SoftCreatR** [comment]
Thank you for that. Too bad, that the original project isn't maintained anymore, but I really needed a replacement.

Now, I'll consider adding branches for older PHP versions, so people can stick at this fork.

**Comment by martinssipenko** [comment]
This was a blocker preventing us from upgrading to composer 2.x, something had to be done :)
