### ISSUE TITLE
Retrieve path of result

### ISSUE THREAD

**Issue by Anyone1990** [SoftCreatR/JSONPath#64]
Hi,

is there any option to get the path that was used to retrieve results by the json path? Reason is that I want to verify if this project meets my requirements (especially in terms of performance). I have a really deep nested (json) array (100+ dimensions). 

One option could be caching the results but it would be nice if there is something similar to getNodePath for DOMXPath implementation.

Best regards

**Comment by SoftCreatR** [comment]
As of now, there's no specific way to retrieve the path.

**Comment by Anyone1990** [comment]
Ok, thanks for your fast reply.
