### ISSUE TITLE
How can I 'and' connect two filter expressions

### ISSUE THREAD

**Issue by bwl21** [SoftCreatR/JSONPath#66]
## Have you spent some time to check if this issue has been raised before?

[x] I have read googled for a similar issue or checked our older issues for a similar bug

### Have you read the [Code of Conduct](https://github.com/SoftCreatR/JSONPath/blob/main/CODE_OF_CONDUCT.md)?

[x] I have read the Code of Conduct

## To Reproduce

```php
<?php
//testjsonpath.php

require 'vendor/autoload.php';

use Flow\JSONPath\JSONPath;


$a = <<< EOT

{
  "grouptypeMemberstatus": {
    "8": {
      "id": "8",
      "gruppentyp_id": "1",
      "bezeichnung": "Teilnehmer"
    },
    "9": {
      "id": "9",
      "gruppentyp_id": "3",
      "bezeichnung": "Teilnehmer"
    }
  }
}

EOT;

$b = json_decode($a);

$c = new JSONPath($b);

$path = "$.grouptypeMemberstatus[?(@.bezeichnung == 'Teilnehmer' and @.gruppentyp_id == '1')].id";
$d = $c->find($path)[0];
var_dump("$path: $d");

$path = "$.grouptypeMemberstatus[?(@.gruppentyp_id == '1')].id";
$e = $c->find($path)[0];
var_dump("$path: $e");

$path = "$.grouptypeMemberstatus[?(@.bezeichnung == 'Teilnehmer')].id";
$f = $c->find($path)[0];
var_dump("$path: $f");



```

## Expected behavior

```
string(88) "$.grouptypeMemberstatus[?(@.bezeichnung == 'Teilnehmer' && @.gruppentyp_id == '1')].id: 8"
string(56) "$.grouptypeMemberstatus[?(@.gruppentyp_id == '1')].id: 8"
string(63) "$.grouptypeMemberstatus[?(@.bezeichnung == 'Teilnehmer')].id: 8"
```

(Write what you thought would happen.)

## Actual Behavior

`php testjsopath.php` yields

```
PHP Notice:  Undefined offset: 0 in ctapishowcase/vendor/softcreatr/jsonpath/src/AccessHelper.php on line 101

Notice: Undefined offset: 0 in ctapishowcase/vendor/softcreatr/jsonpath/src/AccessHelper.php on line 101

string(88) "$.grouptypeMemberstatus[?(@.bezeichnung == 'Teilnehmer' && @.gruppentyp_id == '1')].id: "
string(56) "$.grouptypeMemberstatus[?(@.gruppentyp_id == '1')].id: 8"
string(63) "$.grouptypeMemberstatus[?(@.bezeichnung == 'Teilnehmer')].id: 8"

```
you see that the first entry with the `and` does not yield a result.

## Your Environment

macos Catalina, 

PHP 7.3.25 (cli) (built: Nov 30 2020 14:27:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.25, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.25, Copyright (c) 1999-2018, by Zend Technologies

**Comment by SoftCreatR** [comment]
Him

this library currently doesn't support logical operators like `AND / &&`, `OR / ||`. The only way that comes to my mind are two searches:

1. Search for the first condition (`$.grouptypeMemberstatus[?(@.bezeichnung == 'Teilnehmer')]`)
2. Use the result for a 2nd search with the 2nd condition (`$.[?(@.gruppentyp_id == '1')].id`)

The result of the 2nd search should contain the correct result. Untested example:

```php
<?php
require 'vendor/autoload.php';

$jsonString = '{"grouptypeMemberstatus":{"8":{"id":"8","gruppentyp_id":"1","bezeichnung":"Teilnehmer"},"9":{"id":"9","gruppentyp_id":"3","bezeichnung":"Teilnehmer"}}}';

$jsonPath = new \Flow\JSONPath\JSONPath(json_decode($jsonString));
$search = "$.grouptypeMemberstatus[?(@.bezeichnung == 'Teilnehmer')]";
$resultA = $jsonPath->find($search);

$jsonPath = new \Flow\JSONPath\JSONPath(json_decode(json_encode($resultA)));
$search = "$.[?(@.gruppentyp_id == '1')].id";
$resultB = $jsonPath->find($search);

print_r(['Result A' => $resultA, 'Result B' => $resultB]);
```

**Comment by bwl21** [comment]
Thanks for your reply. I already did a similar workaround by using array_filter for step B. For more complex expressions this might not be sufficient. Do you plan to support logical operators.

I am a bit confused which of the available PHP implementations to use. I started with yours, as it seemed to be the most active one.

**Comment by SoftCreatR** [comment]
It's planned, but there's no ETA. As for the other implementations, you may check this out:;https://github.com/SoftCreatR/JSONPath/wiki/Other-Implementations#php

And this:

https://cburgmer.github.io/json-path-comparison/

**Comment by bwl21** [comment]
Thanks for the hints. I have now migrated to galbar-jsonpath. Such a migration is not trivial, since there are pitfals.

e.g. in galbar  `==` always considers type while yours only checks the value
