### ISSUE TITLE
$.length doesn't work

### ISSUE THREAD

**Issue by Lukazar** [SoftCreatR/JSONPath#68]
Using the following as an example input:
```
[
   1,
   3,
   5
]
```

The following path `$.length` should return `[3]`
Actual result: `[]`

The above is based on the site https://jsonpath.com/ working as described with the example.

**Comment by SoftCreatR** [comment]
There's currently no length function. Instead, simply use `count`:

```php
<?php
use Flow\JSONPath\JSONPath;

require __DIR__ . '/vendor/autoload.php';

$data = ['people' => [
    ['name' => 'Sascha'],
    ['name' => 'Bianca'],
    ['name' => 'Alexander'],
    ['name' => 'Maximilian'],
]];

print_r(count((new JSONPath($data))->find('$.people.*.name')->getData()));

/*
4
*/
```

**Comment by Lukazar** [comment]
Agreed that there are ways around the limitation.  I was hoping for a JSONPath only solution for design reasons.

I am confused though, are you saying that this is a feature request not a bug?  Or -  are you saying its not part of the JSONPath standard and thus shouldn't even be considered?  (Meaning jsonpath.com has deviated from the standard?)

**Comment by SoftCreatR** [comment]
I'm saying, that this specific library currently doesn't support it.

**Comment by Lukazar** [comment]
I got it.  I spent a little time digging around to try to get ahead of my next question, which was "why?".  It seems like this project started off using https://cburgmer.github.io/json-path-comparison/ and taking a consensus approach.  I'm unsure of how strict you are trying to keep this library with regards to the comparisons.  It does appear that any "feature" tagged issues are limited to ones where there is a consensus with a valid output of which this library does not currently support.

I can now see the `$.length` has a consensus output of a normal `$.key` match.

Another issue I have run into is around filters using an `in` clause.  IE: `$.[?(@.key in [1,2,3])]`.  Interestingly in this case there exists code to try to handle that filter.  However - because the code is using `in_array` with a strict compare, the surrounding logic is casting everything to a string.  https://github.com/SoftCreatR/JSONPath/blob/main/src/Filters/QueryMatchFilter.php (lines 55-59).  This is leading to a false positive in the test cases. https://github.com/SoftCreatR/JSONPath/blob/main/tests/QueryTest.php (lines 1233-1238)

This is a very long winded way of me asking would you be against Pull Requests that would perhaps add support for `$.length` and / or dropping the strict compare on `in_array`? I don't want to waste time in supporting something where it goes against your vision of the library.

**Comment by SoftCreatR** [comment]
I'm absolutely open for any improvements :)
