### ISSUE TITLE
Error thrown from JSONPath.php

### ISSUE THREAD

**Issue by TMWagner** [SoftCreatR/JSONPath#73]
## 🐛 Bug Report

When running migration from cron, the following error is thrown
`Deprecated: Calling JSONPath::data() is deprecated, please use JSONPath::getData() instead. in /Users/thomaswagner/hosts/tableau-www/vendor/softcreatr/jsonpath/src/JSONPath.php on line 187`

I am using version 0.7.4

![image](https://user-images.githubusercontent.com/5316689/121398936-c19bc800-c90a-11eb-8116-75901b5cc41f.png)

[ ] I have read the Code of Conduct

## To Reproduce

Run migration implementing jsonpath

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior
Error is thrown apparently from deprecated code.

(Write what happened. Add screenshots, if applicable.)

**Comment by SoftCreatR** [comment]
Btw: https://www.drupal.org/project/feeds_ex/issues/3181642

**Comment by TMWagner** [comment]
You're right.  The error is getting triggered from migrate_plus  `web/modules/contrib/migrate_plus/src/Plugin/migrate_plus/data_parser/JsonPath.php`

**Side note:** I'm on 0.7.4... Going production in a week. Should I upgrade to 0.7.5?

![image](https://user-images.githubusercontent.com/5316689/121402656-032e7200-c90f-11eb-8ef0-d2c1d39767eb.png)

**Comment by TMWagner** [comment]
This issue is upstream from this module - the bug is not here

**Comment by SoftCreatR** [comment]
I would recommend to adjust PHPs error reporting level and wait for the author to upgrade his Plugin.
